# - alias: "Startup Notification"
#   trigger:
#     - platform: event
#       event_type: homeassistant_start
#   action:
#     - service: notify.notify
#       data:
#         title: ok123
#         message: ninini

# - alias: "Send message at lunch time"
#   trigger:
#     platform: time
#     hours: 10
#     minutes: 2
#     seconds: 0
#   action:
#     service: notify.notify
#     data:
#       message: '该吃午饭了'
#       title: '为了健康，请规律饮食！'

# - alias: "test device_tracker"
#   trigger:
#     platform: template
#     entity_id: device_tracker.huawei_p10
#     value_template: "{% if is('device_tracker.huawei_p10', 'home') %}true{% endif %}"  

#   action:
#     - service: notify.app_push
#       data:
#         title: device_tracker
#         message: "home"    


#- alias: "Startup Notification"
#  trigger:
#    - platform: state
#      entity_id: sensor.Temperature
#  action:
#    - service: notify.app_push
#      data:
#        title: ok123
#        message: "{{states.sensor.Temperature.state}} hours"
#        # message: "{{states.device_tracker.youqingkuimbp.attributes.latitude}} value"
#
#
#- alias: "xiaomi Notification"
#  trigger:
#    - platform: state
#      entity_id:
#        - device_tracker.youqingkuimbp
#        - device_tracker.youqingdeiPhone
#  action:
#    - service: notify.sns_email
#      data:
#        target: arn:aws:sns:ap-northeast-2:887438777172:Home_Assistant
#        title: ok123
#        # message: "{{trigger.entity_id}} {{states.device_tracker.youqingkuimbp}} value"
#        message: "{{trigger.entity_id}} {{trigger.entity_id.state}} value"
#
#
#- alias: "Temperature Notification"
#  trigger:
#    - platform: state
#      entity_id:
#        - sensor.temperature_158d0001f538b8
#  action:
#    - service: ifttt.trigger
#      data:
#        event: Temperature
#        Value1: "{{states.sensor.temperature_158d0001f538b8.state}} push"
#    - service: notify.app_push
#      data:
#        title: "Temperature Notification"
#        message: "{{states.sensor.temperature_158d0001f538b8.state}} push"
#
#- alias: "Move Notification"
#  trigger:
#    - platform: state
#      entity_id:
#        - binary_sensor.motion_sensor_158d0001ae8149
#  action:
#    - service: ifttt.trigger
#      data:
#        event: Move
#        Value1: "{{ states.binary_sensor.motion_sensor_158d0001ae8149.to_state.state }} move"
#
#    - service: notify.app_push
#      data:
#        title: "Move Notification"
#        message: "{{states.binary_sensor.motion_sensor_158d0001ae8149.state}} push"


# - alias: If there is motion and its dark turn on the gateway light
#   trigger:
#     platform: state
#     entity_id: binary_sensor.motion_sensor_158d0001ae8149
#     from: 'off'
#     to: 'on' 

#   action:
#     - service: light.turn_on
#       entity_id: light.gateway_light_7811dc64ea36
#       data:
#         brightness: 5              
         


