### 普通通知
- id: "1"
  alias: 温度提醒
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_158d00020ef39b
    value_template: '{{ state.state|round }}'
    above: 28.0
    # below: '30'
    # for:
    #   minutes: 1
  action:
    - service: notify.h5
      data_template:
        title: "温度提醒 {{ states.sensor.temperature_158d00020ef39b.state }}°C"
        message: ""

- id : "12"
  alias: 湿度提醒
  trigger:
    platform: numeric_state
    entity_id: sensor.humidity_158d00020ef39b
    above: '80'
  action:
    - service: notify.h5
      data_template:
        title: "湿度提醒 {{ states.sensor.humidity_158d00020ef39b.state }}%"
        message: ""

- id: "13"
  alias: "minio 触发通知"
  trigger:
    platform: mqtt
    topic: minio
  condition:
    condition: template
    value_template: "{% if 'ObjectCreated' in trigger.payload_json.EventType %} true {% else %} false {% endif %}"
  action:
  - service: ifttt.trigger
    data_template:
      event: rich_notify
      value1: "{% if 'jpg' in  trigger.payload_json.Key %} dafang with image {% else %} dafang with video {% endif%}"
      value2: "https://minio.youqingkui.me/{{trigger.payload_json.Key}}"
      value3: "https://minio.youqingkui.me/{{trigger.payload_json.Key}}"


### 门
- id: "21"
  alias: "门:状态通知"
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0002025c4b
  action:
    - service: notify.h5
      data_template:
        title: "门"
        message: >
          {% if is_state('binary_sensor.door_window_sensor_158d0002025c4b', 'on') %}
            开
            {{now()}}
          {% else %}
            关
            {{now()}}
          {% endif %}

- id: "22"
  alias: "门:记得关"
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0002025c4b
    from: 'off'
    to: 'on'
    for:
      minutes: 1
  action:
    - service: notify.h5
      data_template:
        title: "记得关门哦 \n {{ now() }}"
        message: ""

- id: "23"
  alias: "门:点击通知开门"
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: open_door
  action:
    - service: script.open_door


### 安防
- id: "31"
  alias: "移动:通知"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001f3d0bb
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.youqingkui_note9
    state: "not_home"
  action:
    - service: notify.h5
      data_template:
        title: "检测到移动 \n {{ now() }}"

- id: "32"
  alias: "大方:移动提醒"
  trigger:
    platform: mqtt
    topic: myhome/dafang/motion
    payload: 'ON'
  condition:
    condition: or
    conditions:
    - condition: time
      after: '00:00:00'
      before: '07:00:00'
    - condition: state
      entity_id: device_tracker.youqingkui_note9
      state: "not_home"
  action:
  - service: script.record_video
  - service: notify.h5
    data_template:
      title: "dafang移动 \n {{ now() }}"
      message: ""

- id: "33"
  alias: "大方:移动截图"
  trigger:
    platform: mqtt
    topic: myhome/dafang/motion
    payload: 'ON'
  condition:
    condition: or
    conditions:
    - condition: time
      after: '00:00:00'
      before: '07:00:00'
    - condition: state
      entity_id: device_tracker.youqingkui_note9
      state: "not_home"
  action:
  - service: script.dafang_snapshot2


### WI-FI
- id: "41"
  alias: "WI-FI:设备状态通知"
  trigger:
    platform: event
    event_type: 'state_changed'
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: "{% if 'device_tracker' in trigger.event.data.entity_id  %} true {% else %} false {% endif %}"
    - condition: template
      value_template: "{% if is_state_attr(trigger.event.data.entity_id, 'source_type', 'router')%} true {% else %} false {% endif %}"
    - condition: template
      value_template: "{% if not state_attr(trigger.event.data.entity_id, 'not_notify') %} true {% else %} false {% endif %}"
  action:
  - service: notify.h5
    data_template:
      title: "Wi-Fi"
      message: "{{ state_attr(trigger.event.data.entity_id, 'friendly_name') }} now status {{ states(trigger.event.data.entity_id) }} \n{{now().hour}}"
      data:
        tag: "{{trigger.event.data.entity_id}}-{{states(trigger.event.data.entity_id)}}-{{now().day}}-{{now().hour}}"

- id: "42"
  alias: "WI-Fi:note9连接通知开门"
  trigger:
    platform: state
    entity_id: device_tracker.youqingkui_note9
    from: 'not_home'
    to: 'home'
  action:
    - service: script.open_door
    - service: script.open_door_push

- id: "43"
  alias: "WI-FI:连接打开灯和净化器"
  # 3个手机中任意一台wifi连接,或者门打开
  trigger:
    - platform: state
      entity_id: device_tracker.youqingkui_note9
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.youqingkui
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.rendandeiphone
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002025c4b
      from: 'off'
      to: 'on'
  # 如果时间是18:30 - 23:30，并且灯球是关闭
  condition:
    condition: and
    conditions:
    - condition: time
      after: '18:30:00'
      before: '23:00:00'
    - condition: state
      entity_id: light.xiaomi_philips_smart_led_ball
      state: 'off'
  action:
    # 打开灯球明亮模式
    - service: script.light_bridge_model
    - condition: and
      conditions:
      - condition: state
        entity_id: fan.xiaomi_air_purifier_2s
        state: 'off'
    # 打开空气净化器
    - service: script.open_air_auto_model


### 灯
- id: "51"
  alias: "灯:23点睡觉暖光"
  trigger:
    platform: time
    at: '23:00:00'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.xiaomi_philips_smart_led_ball
      state: 'on'
  action:
    - service: script.light_warm_model

- id: "52"
  alias: "灯:23:50关"
  trigger:
    platform: time
    at: '23:35:00'
  action:
  - service: light.turn_off
    entity_id: light.xiaomi_philips_smart_led_ball

- id: "53"
  alias: "灯:07:50提醒起床"
  trigger:
    platform: time
    at: '07:50:00'
  action:
  - service: light.turn_on
    entity_id: light.xiaomi_philips_smart_led_ball
  - service: script.light_bridge_model
  # 5分钟后自动关灯
  - service: light.xiaomi_miio_set_delayed_turn_off
    data:
      entity_id: light.xiaomi_philips_smart_led_ball
      time_period: 5

- id: "54"
  alias: "灯:离家15分钟关"
  trigger:
    platform: time_pattern
    minutes: '/15'
#    seconds: 00
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.rendandeiphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.youqingkui_note9
      state: 'not_home'
    - condition: state
      entity_id: light.xiaomi_philips_smart_led_ball
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.xiaomi_philips_smart_led_ball
    - service: notify.h5
      data:
        title: "灯球已经自动关闭"
        message: ""

- id: "55"
  alias: '灯:米家开关单击开关'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002108f19_2
      click_type: single
  action:
    service: light.toggle
    entity_id: light.xiaomi_philips_smart_led_ball

- id: "56"
  alias: "灯:米家开关双击切换光模式"
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002108f19_2
      click_type: double
  action:
    - service_template: >
        {% if states.light.xiaomi_philips_smart_led_ball.attributes.scene == 1 %}
          script.light_warm_model
        {% elif states.light.xiaomi_philips_smart_led_ball.attributes.scene == 2 %}
          script.light_warm_model
        {% elif states.light.xiaomi_philips_smart_led_ball.attributes.scene == 3 %}
          script.light_night_model
        {% else %}
          script.light_bridge_model
        {% endif%}

- id: "57"
  alias: "台灯:aqara开关单击切换"
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001eb6251
      click_type: single
  action:
    - service: light.toggle
      entity_id: light.philips_eyecare_smart_lamp_2_2
    - condition: and
      conditions:
      - condition: state
        entity_id: light.philips_eyecare_smart_lamp_2_2
        state: 'off'
    - service: light.turn_off
      entity_id: light.philips_eyecare_smart_lamp_2_ambient_light_2

- id: "58"
  alias: "台灯:aqara开关双击主灯与环境灯切换"
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001eb6251
      click_type: double
  action:
    - service: light.toggle
      entity_id: light.philips_eyecare_smart_lamp_2_ambient_light_2
    - condition: and
      conditions:
      - condition: state
        entity_id: light.philips_eyecare_smart_lamp_2_ambient_light_2
        state: 'on'
    - service: light.turn_on
      entity_id: light.philips_eyecare_smart_lamp_2_2

- id: "59"
  alias: "台灯:状态通知"
  trigger:
    platform: state
    entity_id: light.philips_eyecare_smart_lamp_2_2, light.philips_eyecare_smart_lamp_2_ambient_light_2
  action:
    - service: notify.h5
      data_template:
        title: 台灯
        message: >
          "主灯:{{states.light.philips_eyecare_smart_lamp_2_2.state}},副灯{{states.light.philips_eyecare_smart_lamp_2_ambient_light_2.state}}"


### 空调
- id: "61"
  alias: "空调:离家10分钟关"
  trigger:
    platform: time_pattern
    minutes: '/10'
    seconds: 00
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.rendandeiphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.youqingkui_note9
      state: 'not_home'
    - condition: state
      entity_id: binary_sensor.airconditioning
      state: 'on'
  action:
    - service: script.close_airconditioning

- id: "62"
  alias: "空调:状态提醒"
  trigger:
    platform: state
    entity_id: sensor.air_test
  action:
    - service: script.airconditioning_status


### 空气净化器
- id: "71"
  alias: "空净:18点开"
  trigger:
    platform: time
    at: '18:00:00'
  condition:
    condition: state
    entity_id: fan.xiaomi_air_purifier_2s
    state: 'off'
  action:
    - service: script.open_air_auto_model

- id: "72"
  alias: "空净:23:30睡眠模式"
  trigger:
    platform: time
    at: '23:30:00'
  condition:
    condition: state
    entity_id: fan.xiaomi_air_purifier_2s
    state: 'on'
  action:
   - service: script.air_silent_model

- id: "73"
  alias: "空净:离家30分钟关"
  trigger:
    platform: time_pattern
    minutes: 30
#    seconds: 00
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.rendandeiphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.youqingkui_note9
      state: 'not_home'
    - condition: state
      entity_id: fan.xiaomi_air_purifier_2s
      state: 'on'
  action:
    - service: fan.turn_off
      entity_id: fan.xiaomi_air_purifier_2s

- id: "74"
  alias: "空净:空气质量提醒"
  trigger:
    platform: numeric_state
    entity_id: fan.xiaomi_air_purifier_2s
    value_template: '{{ state.attributes.aqi|round }}'
    above: 30.0
    # below: '30'
    # for:
    #   minutes: 1
  action:
    - service: script.now_air_quality

- id: "75"
  alias: "空净:模式状态"
  initial_state: true
  trigger:
    platform: time_pattern
    seconds: /5
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.xiaomi_ap_mode
      option: >
        {% if states.fan.xiaomi_air_purifier_2s.attributes.mode == "auto" %}自动
        {% elif states.fan.xiaomi_air_purifier_2s.attributes.mode == "silent" %}睡眠
        {% elif states.fan.xiaomi_air_purifier_2s.attributes.mode == "favorite" %}最爱
        {% elif states.fan.xiaomi_air_purifier_2s.attributes.mode == "idle" %}待机
        {% endif %}

- id: "76"
  alias: "空净:设置模式"
  initial_state: true
  trigger:
    platform: state
    entity_id: input_select.xiaomi_ap_mode
  action:
    service: fan.turn_on
    data_template:
      entity_id: fan.xiaomi_air_purifier_2s
      speed: >
        {% if states.input_select.xiaomi_ap_mode.state == "自动" %}Auto
        {% elif states.input_select.xiaomi_ap_mode.state == "睡眠" %}Silent
        {% elif states.input_select.xiaomi_ap_mode.state == "最爱" %}Favorite
        {% elif states.input_select.xiaomi_ap_mode.state == "待机" %}Idle
        {% endif %}

#- alias: xiaomi_ap_get_led
#  initial_state: true
#  trigger:
#    platform: time_pattern
#    seconds: /5
#  action:
#    service: input_select.select_option
#    data_template:
#      entity_id: input_select.xiaomi_ap_led
#      option: >
#        {% if states.fan.xiaomi_air_purifier_2s.attributes.led_brightness == 0 %}亮光
#        {% elif states.fan.xiaomi_air_purifier_2s.attributes.led_brightness == 1 %}微光
#        {% elif states.fan.xiaomi_air_purifier_2s.attributes.led_brightness == 2 %}关闭
#        {% endif %}
#
#- alias: xiaomi_ap_set_led
#  initial_state: true
#  trigger:
#    platform: state
#    entity_id: input_select.xiaomi_ap_led
#  action:
#    service: fan.xiaomi_miio_set_led_brightness
#    data_template:
#      entity_id: fan.xiaomi_air_purifier_2s
#      brightness: >
#        {% if states.input_select.xiaomi_ap_led.state == "亮光" %}0
#        {% elif states.input_select.xiaomi_ap_led.state == "微光" %}1
#        {% elif states.input_select.xiaomi_ap_led.state == "关闭" %}2
#        {% endif %}



