### 普通通知
- alias: temperature_alert
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_158d00020ef39b
    value_template: '{{ state.state|round }}'
    above: 28.0
    # below: '30'
    # for:
    #   minutes: 1
  action:
    - service: notify.h5
      data_template:
        title: "温度提醒 {{ states.sensor.temperature_158d00020ef39b.state }}°C"
        message: ""

- alias: humidity_alert
  trigger:
    platform: numeric_state
    entity_id: sensor.humidity_158d00020ef39b
    above: '80'
  action:
    - service: notify.h5
      data_template:
        title: "湿度提醒 {{ states.sensor.humidity_158d00020ef39b.state }}%"
        message: ""

- alias: minio_notify
  trigger:
    platform: mqtt
    topic: minio
  condition:
    condition: template
    value_template: "{% if 'ObjectCreated' in trigger.payload_json.EventType %} true {% else %} false {% endif %}"
  action:
  - service: ifttt.trigger
    data_template:
      event: rich_notify
      value1: "{% if 'jpg' in  trigger.payload_json.Key %} dafang with image {% else %} dafang with video {% endif%}"
      value2: "https://minio.youqingkui.me/{{trigger.payload_json.Key}}"
      value3: "https://minio.youqingkui.me/{{trigger.payload_json.Key}}"


### 门
- alias: door_status
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0002025c4b
  action:
    - service: notify.h5
      data_template:
        title: "门"
        message: >
          {% if is_state('binary_sensor.door_window_sensor_158d0002025c4b', 'on') %}
            开
            {{now()}}
          {% else %}
            关
            {{now()}}
          {% endif %}

- alias: remind_door
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0002025c4b
    from: 'off'
    to: 'on'
    for:
      minutes: 1
  action:
    - service: notify.h5
      data_template:
        title: "记得关门哦 \n {{ now() }}"
        message: ""

- alias: connec_wifi_open_door
  trigger:
    platform: state
    entity_id: device_tracker.youqingkuinote9
    from: 'not_home'
    to: 'home'
  action:
    - service: script.open_door
    - service: script.open_door_push

- alias: open_door_action
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: open_door
  action:
    - service: script.open_door


### 安防
- alias: notify_move
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001f3d0bb
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.youqingkuinote9
    state: "not_home"
  action:
    - service: notify.h5
      data_template:
        title: "检测到移动 \n {{ now() }}"

- alias: motion_detector
  trigger:
    platform: mqtt
    topic: myhome/dafang/motion
    payload: 'ON'
  condition:
    condition: or
    conditions:
    - condition: time
      after: '00:00:00'
      before: '07:00:00'
    - condition: state
      entity_id: device_tracker.youqingkuinote9
      state: "not_home"
  action:
  - service: script.record_video
  - service: notify.h5
    data_template:
      title: "dafang移动 \n {{ now() }}"
      message: ""

- alias: motion_detector_snapshot
  trigger:
    platform: mqtt
    topic: myhome/dafang/motion
    payload: 'ON'
  condition:
    condition: or
    conditions:
    - condition: time
      after: '00:00:00'
      before: '07:00:00'
    - condition: state
      entity_id: device_tracker.youqingkuinote9
      state: "not_home"
  action:
  - service: script.dafang_snapshot2


### WI-FI
- alias: device_online_notify
  trigger:
    platform: event
    event_type: 'state_changed'
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: "{% if 'device_tracker' in trigger.event.data.entity_id  %} true {% else %} false {% endif %}"
    - condition: template
      value_template: "{% if is_state_attr(trigger.event.data.entity_id, 'source_type', 'router')%} true {% else %} false {% endif %}"
  action:
  - service: notify.h5
    data_template:
      title: "Wi-Fi"
      message: "{{ state_attr(trigger.event.data.entity_id, 'friendly_name') }} now status {{ states(trigger.event.data.entity_id) }} \n{{now().hour}}"
      data:
        tag: "{{trigger.event.data.entity_id}}-{{states(trigger.event.data.entity_id)}}-{{now().day}}-{{now().hour}}"


### 灯
- alias: auto_light_night
  trigger:
    platform: time
    at: '23:00:00'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.xiaomi_philips_smart_led_ball
      state: 'on'
  action:
    - service: script.light_warm_model

- alias: sleep_close_light
  trigger:
    platform: time
    at: '23:35:00'
  action:
  - service: light.turn_off
    entity_id: light.xiaomi_philips_smart_led_ball

- alias: eight_wake_up
  trigger:
    platform: time
    at: '07:50:00'
  action:
  - service: light.turn_on
    entity_id: light.xiaomi_philips_smart_led_ball
  - service: script.light_bridge_model
  # 5分钟后自动关灯
  - service: light.xiaomi_miio_set_delayed_turn_off
    data:
      entity_id: light.xiaomi_philips_smart_led_ball
      time_period: 5

- alias: leave_close_light
  trigger:
    platform: time
    minutes: '/10'
    seconds: 00
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.rendandeiphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.youqingkuinote9
      state: 'not_home'
    - condition: state
      entity_id: light.xiaomi_philips_smart_led_ball
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.xiaomi_philips_smart_led_ball
    - service: notify.h5
      data:
        title: "灯球已经自动关闭"
        message: ""

#- alias: toggle_led_ball
#  trigger:
#    platform: event
#    event_type: click
#    event_data:
#      entity_id: binary_sensor.switch_158d0002108f19
#      click_type: single
#  action:
#    service: light.toggle
#    entity_id: light.xiaomi_philips_smart_led_ball
#
#- alias: ready_sleep
#  trigger:
#    platform: event
#    event_type: long_click_press
#    event_data:
#      entity_id: binary_sensor.switch_158d0002108f19
#      click_type: single
#  action:
#    service: script.light_night_sleep

#- alias: button_toggle_light_ball
#  trigger:
#    platform: event
#    event_type: xiaomi_aqara.click
#    event_data:
#      entity_id: binary_sensor.switch_158d0001eb6251
#      click_type: single
#  action:
#    - service: light.toggle
#      entity_id: light.xiaomi_philips_smart_led_ball
#
#- alias: button_light_bridge_model
#  trigger:
#    platform: event
#    event_type: xiaomi_aqara.click
#    event_data:
#      entity_id: binary_sensor.switch_158d0001eb6251
#      click_type: double
#  action:
#    - service: script.light_bridge_model
#
#- alias: button_light_warm_model
#  trigger:
#    platform: event
#    event_type: xiaomi_aqara.click
#    event_data:
#      entity_id: binary_sensor.switch_158d0001eb6251
#      click_type: double
#  action:
#    - service: script.light_warm_model


### 空调
- alias: auto_close_airconditioning
  trigger:
    platform: time
    minutes: '/10'
    seconds: 00
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.rendandeiphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.youqingkuinote9
      state: 'not_home'
    - condition: state
      entity_id: binary_sensor.airconditioning
      state: 'on'
  action:
    - service: script.close_airconditioning

- alias: air_status_change
  trigger:
    platform: state
    entity_id: sensor.air_test
  action:
    - service: script.airconditioning_status


### 空气净化器
- alias: auto_open_air
  trigger:
    platform: time
    at: '18:00:00'
  condition:
    condition: state
    entity_id: fan.xiaomi_air_purifier_2s
    state: 'off'
  action:
    - service: script.open_air_auto_model

- alias: auto_sleep_model_air
  trigger:
    platform: time
    at: '23:30:00'
  condition:
    condition: state
    entity_id: fan.xiaomi_air_purifier_2s
    state: 'on'
  action:
   - service: script.air_silent_model

- alias: auto_close_air
  trigger:
    platform: time
    minutes: 30
    seconds: 00
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.rendandeiphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.youqingkuinote9
      state: 'not_home'
    - condition: state
      entity_id: fan.xiaomi_air_purifier_2s
      state: 'on'
  action:
    - service: fan.turn_off
      entity_id: fan.xiaomi_air_purifier_2s

- alias: air_quality_alert
  trigger:
    platform: numeric_state
    entity_id: fan.xiaomi_air_purifier_2s
    value_template: '{{ state.attributes.aqi|round }}'
    above: 15.0
    # below: '30'
    # for:
    #   minutes: 1
  action:
    - service: script.now_air_quality


# 综合自动化
- alias: back_home_open_air
  # 3个手机中任意一台wifi连接,或者门打开
  trigger:
    - platform: state
      entity_id: device_tracker.youqingkuinote9
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.youqingkui
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.rendandeiphone
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002025c4b
      from: 'off'
      to: 'on'
  # 如果时间是18:30 - 23:30，并且灯球是关闭
  condition:
    condition: and
    conditions:
    - condition: time
      after: '18:30:00'
      before: '23:00:00'
    - condition: state
      entity_id: light.xiaomi_philips_smart_led_ball
      state: 'off'
  action:
    # 打开灯球明亮模式
    - service: script.light_bridge_model
    - condition: and
      conditions:
      - condition: state
        entity_id: fan.xiaomi_air_purifier_2s
        state: 'off'
    # 打开空气净化器
    - service: script.open_air_auto_model



