homeassistant:
#  auth_providers:
#   - type: legacy_api_password
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home1_latitude
  longitude: !secret home1_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs: /home/pi/.homeassistant/www/snapshot/


# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:



# Enables configuration UI
cloud:
  alexa:
    filter:
      include_entities:
        - light.xiaomi_philips_smart_led_ball
        - light.gateway_light_7811dc64ea36
      include_domains:
        - switch
    entity_config:
      light.xiaomi_philips_smart_led_ball:
        name: led ball
        description: The light in the living room
      light.gateway_light_7811dc64ea36:
        name: gateway light
        description: The gateway light in the living room
config:

http:
#  api_password: youqingkui
  base_url: 192.168.31.238:8123
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  use_x_forwarded_for: True
  trusted_proxies:
#    - 127.0.0.1
#    - ::1
  trusted_networks:
#    - 127.0.0.1
#    - ::1
#    - 192.168.31.0/24
#    - fd00::/8

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
#  - platform: command_line
#    name: CPU_1mine
#    command: "uptime | awk '{print $8}' | sed 's/,//g'"
#    unit_of_measurement: "%"
#    value_template: '{{ value | multiply(100) | round(2) }}'

  - platform: command_line
    name: air_test
    command: "/home/pi/homeassistant/bin/python /home/pi/.homeassistant/custom_components/airconditioningcompanion.py mode"
  - platform: cpuspeed
  - platform: systemmonitor
    resources:
#      - type: disk_use_percent
#        arg: /home
#      - type: memory_free
#      - type: network_in
#        arg: wlan0
#      - type: network_out
#        arg: wlan0
#      - type: process
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use
#  - platform: time_date
#    display_options:
#      - 'time'
#      - 'date'
#      - 'date_time'
#      - 'time_date'
#      - 'time_utc'
#      - 'beat'
#  - platform: darksky
#    api_key: !secret darksky_key
#    update_interval:
#      days: 0
#      hours: 0
#      minutes: 0
#      seconds: 30
#      milliseconds: 0
#    monitored_conditions:
#      - summary
#      - icon
#      - nearest_storm_distance
#      - precip_intensity
#      - temperature
#      - apparent_temperature
#      - wind_speed
#      - wind_bearing
#      - cloud_cover
#      - humidity
#      - pressure
#      - visibility
#      - daily_summary
#      - temperature_max
#      - temperature_min
#      - apparent_temperature_max
#      - apparent_temperature_min
#      - precip_intensity_max
#  - platform: mqtt
#    state_topic: 'office/sensor1'
#    name: 'Temperature'
#    unit_of_measurement: '°C'
#    value_template: '{{ value_json.temperature }}'
#  - platform: mqtt
#    state_topic: 'office/sensor1'
#    name: 'Humidity'
#    unit_of_measurement: '%'
#    value_template: '{{ value_json.humidity }}'




#microsoft_face:
#  api_key: !secret microsoft_face_api_key
#
#image_processing:
##  - platform: microsoft_face_detect
#  - platform: aws_face
#    source:
#      - entity_id: camera.ip_webcam

ifttt:
  key: !secret ifttt_key

notify:
  - name: Pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key
  - platform: html5
    name: h5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

device_tracker:
  - platform: xiaomi
    host: 192.168.31.1
    password: !secret mi_route
    consider_home: 120
  - platform: owntracks_http
  - platform: icloud
    username: !secret icloud_user
    password: !secret icloud_password
    account_name: youqingicloud
    max_interval: 60

xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi_aqara_mac
      key: !secret xiaomi_aqara_key

#climate:
#  - platform: xiaomi_miio
#    name: air
#    host: 192.168.31.55
#    token: !secret xiaomi_miio_climate
#    target_sensor: sensor.temperature_158d00020ef39b
#    scan_interval: 60

input_text:
  text1:
    name: snapshot
    initial: ""

fan:
  - platform: xiaomi_miio
    name: Xiaomi Air Purifier 2s
    host: 192.168.31.219
    token: !secret air_purifier_token

python_script:

switch:
  - platform: command_line
    switches:
      kitchen_light:
        command_on: "python /home/pi/.homeassistantustom_components/love_music.py START"
        command_off: "python /home/pi/.homeassistantustom_components/love_music.py NEXT"

  - platform: xiaomi_miio
    name: Original Xiaomi Mi Smart WiFi Socket
    host: 192.168.31.234
#    host: chuangmi-plug-v1_miio11440510
    token: !secret xiaomi_wifi_socket


camera:
#  - platform: ffmpeg
#  name: DaFang3
#   input: -rtsp_transport tcp -i rtsp://192.168.31.187:8554/unicast
#   extra_arguments: -pred 1 -q:v 2
  - platform: generic
    name: DaFang3
    username: root
    password: ismart12
    authentication: basic
    still_image_url: https://192.168.31.187/cgi-bin/currentpic.cgi
    verify_ssl: false
    scan_interval: 5
#  - platform: ffmpeg
#    name: XiaoFang
#    input: -rtsp_transport tcp -i rtsp://192.168.31.187:8554/unicast
#    extra_arguments: -pred 1 -q:v 2


#mqtt:
#  # broker: 127.0.0.1
#  discovery: true
#  discovery_prefix: homeassistant
#  password: !secret http_password
##  protocol: 3.1.1

mqtt:
  broker: !secret aws_broker
  port: 8883
  discovery: true
  discovery_prefix: homeassistant
  client_id: basicPubSub
  certificate: /home/pi/.homeassistant/connect_device_package/root-CA.crt
  client_key: /home/pi/.homeassistant/connect_device_package/HA.private.key
  client_cert: /home/pi/.homeassistant/connect_device_package/HA.cert.pem
  tls_version: '1.2'
  tls_insecure: false

shell_command:
  record_video: "bash /home/pi/.homeassistant/dafang_hack/record_video.sh"
  close_airconditioning: "/home/pi/homeassistant/bin/python /home/pi/.homeassistant/custom_components/airconditioningcompanion.py off"
  open_airconditioning: "/home/pi/homeassistant/bin/python /home/pi/.homeassistant/custom_components/airconditioningcompanion.py on"
  open_door: "bash /home/pi/.homeassistant/custom_components/open_door.sh"

binary_sensor:
  - platform: command_line
    command: '/home/pi/homeassistant/bin/python /home/pi/.homeassistant/custom_components/airconditioningcompanion.py'
    name: 'airconditioning'
    device_class: power
    payload_on: 1
    payload_off: 0

light:
  - platform: xiaomi_miio
    name: Xiaomi Philips Smart LED Ball
    host: 192.168.31.15
    token: !secret philips_light2_token
  - platform: xiaomi_miio
    name: PHILIPS EYECARE SMART LAMP 2
    host: 192.168.31.253
    token: !secret philips_lamp_token
    model: philips.light.sread1


zone:
  - name: Work1
    latitude: !secret work1_latitude
    longitude: !secret work1_longitude
    radius: 500

  - name: Work2
    latitude: !secret work2_latitude
    longitude: !secret work2_longitude
    radius: 500

# Text to speech
tts:
  - platform: google
  - platform: amazon_polly
    aws_access_key_id: !secret amazon_polly_key
    aws_secret_access_key: !secret amazon_polly_access_key
    region_name: ap-northeast-2
    voice: Zhiyu

logger:
  default: info
  logs:
    homeassistant.components.mqtt: error
    hbmqtt.broker: error
    hbmqtt.mqtt.protocol.handler: error
    transitions.core: warn

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# switch:
#   - platform: xiaomi_miio
#     name: Original Xiaomi Mi Smart WiFi Socket
#     host: 192.168.31.234
#     token:

# light:
#   - platform: xiaomi_miio
#     name: Xiaomi Philips Smart LED Ball
#     host: 192.168.31.19
#     token:


#notify:
#  - name: app_push
#    platform: instapush
#    api_key: !secret instapush_api_key
#    app_secret: !secret instapush_app_secret
#    event: msg
#    tracker: state
#
#  - name: sns_email
#    platform: aws_sns
#    aws_access_key_id: !secret aws_access_key_id
#    aws_secret_access_key: !secret aws_secret_access_key
#    region_name: 'ap-northeast-2'
#
#calendar:
#  - platform: todoist
#    token: !secret todoist_token
#    custom_projects:
#      - name: 'Inbox'
#      - name: 'Due Today'
#        due_date_days: 0
#      - name: 'Due This Week'
#        due_date_days: 7

# calendar:
#   - platform: caldav
#     url: !secret cldav_url

#mqtt:
#  broker: !secret aws_broker
#  port: 8883
#  client_id: test
#  certificate: /home/pi/.homeassistant/connect_device_package/root-CA.crt
#  client_key: /home/pi/.homeassistant/connect_device_packagee/HA.private.key
#  client_cert: /home/pi/.homeassistant/connect_device_package/HA.cert.pem
#  protocol: 3.1.1
#
#hello_mqtt:
#  topic: some_mqtt/topic/here
# dafang_motion_snapshot:
#   topic: myhome/dafang/motion/snapshot
#aws_rekognition:
#  region_name: us-east-1
#  aws_access_key_id: !secret aws_access_key_id
#  aws_secret_access_key: !secret aws_secret_access_key

# android_ip_webcam:
#   - host: 192.168.31.250
#     port: 8080
#     sensors:
#       - audio_connections
#       - battery_level
#       - battery_temp
#       - battery_voltage
#       - light
#       - motion
#       - pressure
#     switches:
#       - exposure_lock
#       - ffc
#       - focus
#       - gps_active
#       - night_vision
#       - overlay
#       - torch
#       - whitebalance_lock
#       - video_recording

# switch:
#   - platform: command_line
#     switches:
#       Play_Music:
#         # command_on: 1
#         # command_off: 0
#         command_on: "python /home/pi/.homeassistantustom_components/love_music.py START"
#         command_off: "python /home/pi/.homeassistantustom_components/love_music.py NEXT"
